### ISSUE TITLE
Restart Auxiliary Applications

### ISSUE THREAD

**Issue by painfulsedative** [cjmurph/PmsService#13]
Current, this app has a built in feature that allows starting subsequent apps during launch.  I think it would be a good feature to add a means to stop, start, and maybe restart those applications in case they run into any issues that make them nonresponsive.  The app I use through the Aux App section is PlexPy if you wanted something to test functionality with.  

Thanks!

**Comment by JeanGionet** [comment]
how are you starting PlexPy with the Aux App? I've tried it and it never launches for me after my computer reboots. PmsService works fine after a reboot.

**Comment by painfulsedative** [comment]
goto [https://forums.plex.tv/discussion/comment/1170733#Comment_1170733](url) and scroll up for the config I used.  I haven't had any problems and it works amazingly.

**Comment by JeanGionet** [comment]
Thanks! I stumbled on that post right after I posted on here! (that's why I had deleted my previous comment) ;)

**Comment by painfulsedative** [comment]
oh lol it took me a bit to get the link so i guess i was a little slow :)

**Comment by cjmurph** [comment]
Added in 1.1.1. Thanks.
