### ISSUE TITLE
Left clicking notification icon opens menu

### ISSUE THREAD

**Issue by kravena** [cjmurph/PmsService#16]
With the new functionality to double left click to open Plex, left clicking the icon also opens the menu. The menu should only open on right click.

When Plex is opened using the notification icon, the menu remains open in the notification area and is difficult to close.

**Comment by cjmurph** [comment]
Actually, I always had it open on left or right click. the double click is new. I agree that now there is double click, the left click shouldn't do anything. I'll remove the event.

**Comment by cjmurph** [comment]
Resolved. It'll get rolled out in the next release
