### ISSUE TITLE
[Request] Ability to have custom menu options added to notification icon menu

### ISSUE THREAD

**Issue by kravena** [cjmurph/PmsService#17]
Additional supporting applications can be added to Plex, such as PlexPY. However it is difficult to launch these, as they are based off an internal web server instead of an application in it's own right. Can a link be added to the menu to launch http://localhost:8181 (for PlexPY) if the application is found to be present or can be enabled in the settings ?

**Comment by painfulsedative** [comment]
this is how i have plexpy configured, if it helps - http://prnt.sc/dejcai

**Comment by cjmurph** [comment]
I could add an option per aux application to have a menu item that performs a custom action.
I'll look into it.

**Comment by cjmurph** [comment]
This is done, a while ago. thanks for the suggestion.
