### ISSUE TITLE
Shell_NotifyIcon(NIM_ADD) failed: 0x0

### ISSUE THREAD

**Issue by seanvree** [cjmurph/PmsService#19]
OS:  Windows 10U
PMS: Version 1.3.3.3148 

I keep getting this error in my PMS logs:

Dec 16, 2016 12:08:13.354	WARN	Shell_NotifyIcon(NIM_ADD) failed: 0x0
Dec 16, 2016 12:08:08.353	WARN	Shell_NotifyIcon(NIM_ADD) failed: 0x0
Dec 16, 2016 12:08:03.356	WARN	Shell_NotifyIcon(NIM_ADD) failed: 0x0
Dec 16, 2016 12:07:58.354	WARN	Shell_NotifyIcon(NIM_ADD) failed: 0x0
Dec 16, 2016 12:07:53.350	WARN	Shell_NotifyIcon(NIM_ADD) failed: 0x0

I did a quick search and found this thread:

https://forums.plex.tv/discussion/115336/pms-log-keeps-disks-awake-due-to-shell-notifyicon-failed

So, should I add that "-noninteractive" to the PlexService start parameters?

Thanks,

**Comment by cjmurph** [comment]
What version of the service are you using? The service uses that argument already. Can you paste the service logs in here too please

**Comment by seanvree** [comment]
@cjmurph - Ican't seem to find the service version anywhere.  

I'm running the latest from the repo tho. 

Also, not sure if it's internal, but in the actual service manager in windows the "Start parameters" field is blank. Not sure if that's where it would be.  

Logs:

12/1/2016 1:59:06 AM: Attempting to start Plex
12/1/2016 1:59:06 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/1/2016 1:59:06 AM: Plex Media Server Started.
12/1/2016 1:59:06 AM: Plex Service Started
12/1/2016 3:04:41 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/1/2016 3:04:41 AM: Attempting to start Plex
12/1/2016 3:04:42 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/1/2016 3:04:42 AM: Plex Media Server Started.
12/1/2016 3:04:42 AM: Plex Service Started
12/5/2016 12:30:16 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/5/2016 12:30:16 AM: Attempting to start Plex
12/5/2016 12:30:17 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/5/2016 12:30:17 AM: Plex Media Server Started.
12/5/2016 12:30:17 AM: Plex Service Started
12/5/2016 4:18:45 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/5/2016 4:18:45 PM: Attempting to start Plex
12/5/2016 4:18:45 PM: Plex Service Started
12/5/2016 4:18:45 PM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/5/2016 4:18:45 PM: Plex Media Server Started.
12/5/2016 11:14:16 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/5/2016 11:14:16 PM: Attempting to start Plex
12/5/2016 11:14:16 PM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/5/2016 11:14:16 PM: Plex Media Server Started.
12/5/2016 11:14:16 PM: Plex Service Started
12/6/2016 2:36:11 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 2:36:11 AM: Attempting to start Plex
12/6/2016 2:36:11 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 2:36:11 AM: Plex Media Server Started.
12/6/2016 2:36:11 AM: Plex Service Started
12/6/2016 3:58:24 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 3:58:24 AM: Attempting to start Plex
12/6/2016 3:58:25 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 3:58:25 AM: Plex Media Server Started.
12/6/2016 3:58:25 AM: Plex Service Started
12/6/2016 4:04:13 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 4:04:13 AM: Attempting to start Plex
12/6/2016 4:04:13 AM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 4:04:13 AM: Plex Media Server Started.
12/6/2016 4:04:13 AM: Plex Service Started
12/6/2016 4:30:56 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 4:30:56 PM: Attempting to start Plex
12/6/2016 4:30:56 PM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 4:30:56 PM: Plex Media Server Started.
12/6/2016 4:30:56 PM: Plex Service Started
12/6/2016 6:31:26 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 6:31:26 PM: Attempting to start Plex
12/6/2016 6:31:26 PM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 6:31:26 PM: Plex Media Server Started.
12/6/2016 6:31:26 PM: Plex Service Started
12/6/2016 11:48:01 PM: Plex Media Server has stopped!
12/6/2016 11:48:01 PM: PlexScriptHost Stopped.
12/6/2016 11:48:01 PM: PlexTranscoder Stopped.
12/6/2016 11:49:03 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 11:49:03 PM: Attempting to start Plex
12/6/2016 11:49:03 PM: Plex Media Server version is 1.3.0.3059. Can use startup argument.
12/6/2016 11:49:03 PM: Plex Media Server Started.
12/6/2016 11:51:13 PM: Killing Plex.
12/6/2016 11:51:13 PM: Plex Media Server has stopped!
12/6/2016 11:51:13 PM: PlexScriptHost Stopped.
12/6/2016 11:51:23 PM: Plex Service Stopped
12/6/2016 11:51:26 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/6/2016 11:51:26 PM: Successfully removed auto start entry from registry
12/6/2016 11:51:26 PM: Attempting to start Plex
12/6/2016 11:51:26 PM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/6/2016 11:51:26 PM: Plex Media Server Started.
12/6/2016 11:51:27 PM: There is already a listener on IP endpoint 0.0.0.0:8787. This could happen if there is another application already listening on this endpoint or if you have multiple service endpoints in your service host with the same IP endpoint but with incompatible binding configurations.
12/6/2016 11:51:27 PM: Plex Service Started
12/7/2016 4:44:39 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/7/2016 4:44:39 AM: Plex Service Started
12/7/2016 4:44:39 AM: Attempting to start Plex
12/7/2016 4:44:39 AM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/7/2016 4:44:39 AM: Plex Media Server Started.
12/7/2016 5:18:51 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/7/2016 5:18:51 AM: Attempting to start Plex
12/7/2016 5:18:51 AM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/7/2016 5:18:51 AM: Plex Media Server Started.
12/7/2016 5:18:51 AM: Plex Service Started
12/7/2016 5:29:41 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/7/2016 5:29:41 AM: Attempting to start Plex
12/7/2016 5:29:41 AM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/7/2016 5:29:41 AM: Plex Media Server Started.
12/7/2016 5:29:41 AM: Plex Service Started
12/7/2016 5:35:52 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/7/2016 5:35:52 AM: Attempting to start Plex
12/7/2016 5:35:52 AM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/7/2016 5:35:52 AM: Plex Media Server Started.
12/7/2016 5:35:52 AM: Plex Service Started
12/8/2016 3:20:38 PM: Killing Plex.
12/8/2016 3:20:38 PM: Plex Media Server has stopped!
12/8/2016 3:20:38 PM: PlexScriptHost Stopped.
12/8/2016 3:20:38 PM: Plex Service Stopped
12/8/2016 3:20:41 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/8/2016 3:20:41 PM: Attempting to start Plex
12/8/2016 3:20:41 PM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/8/2016 3:20:41 PM: Plex Media Server Started.
12/8/2016 3:20:41 PM: Plex Service Started
12/8/2016 3:28:04 PM: Plex Media Server has stopped!
12/8/2016 3:28:04 PM: PlexScriptHost Stopped.
12/8/2016 3:29:27 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/8/2016 3:29:27 PM: Attempting to start Plex
12/8/2016 3:29:27 PM: Plex Media Server version is 1.3.1.3102. Can use startup argument.
12/8/2016 3:29:27 PM: Plex Media Server Started.
12/8/2016 3:53:33 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/8/2016 3:53:33 PM: Successfully removed auto start entry from registry
12/8/2016 3:53:33 PM: Attempting to start Plex
12/8/2016 3:53:33 PM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/8/2016 3:53:33 PM: Plex Media Server Started.
12/8/2016 3:53:33 PM: Plex Service Started
12/9/2016 5:33:40 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/9/2016 5:33:40 PM: Attempting to start Plex
12/9/2016 5:33:40 PM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/9/2016 5:33:40 PM: Plex Media Server Started.
12/9/2016 5:33:41 PM: Plex Service Started
12/9/2016 5:35:29 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/9/2016 5:35:29 PM: Attempting to start Plex
12/9/2016 5:35:29 PM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/9/2016 5:35:29 PM: Plex Media Server Started.
12/9/2016 5:35:29 PM: Plex Service Started
12/12/2016 9:58:07 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/12/2016 9:58:07 PM: Attempting to start Plex
12/12/2016 9:58:07 PM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/12/2016 9:58:07 PM: Plex Media Server Started.
12/12/2016 9:58:07 PM: Plex Service Started
12/13/2016 12:14:13 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/13/2016 12:14:13 AM: Attempting to start Plex
12/13/2016 12:14:13 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/13/2016 12:14:13 AM: Plex Media Server Started.
12/13/2016 12:14:13 AM: Plex Service Started
12/14/2016 12:27:27 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/14/2016 12:27:27 AM: Attempting to start Plex
12/14/2016 12:27:27 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/14/2016 12:27:27 AM: Plex Media Server Started.
12/14/2016 12:27:27 AM: Plex Service Started
12/14/2016 12:28:51 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/14/2016 12:28:51 AM: Attempting to start Plex
12/14/2016 12:28:51 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/14/2016 12:28:51 AM: Plex Media Server Started.
12/14/2016 12:28:51 AM: Plex Service Started
12/14/2016 1:44:14 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/14/2016 1:44:14 AM: Attempting to start Plex
12/14/2016 1:44:14 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/14/2016 1:44:14 AM: Plex Media Server Started.
12/14/2016 1:44:14 AM: Plex Service Started
12/14/2016 4:00:36 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/14/2016 4:00:36 AM: Attempting to start Plex
12/14/2016 4:00:36 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/14/2016 4:00:36 AM: Plex Media Server Started.
12/14/2016 4:00:36 AM: Plex Service Started
12/14/2016 4:14:59 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/14/2016 4:14:59 AM: Attempting to start Plex
12/14/2016 4:14:59 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/14/2016 4:14:59 AM: Plex Media Server Started.
12/14/2016 4:14:59 AM: Plex Service Started
12/15/2016 5:17:35 AM: Killing Plex.
12/15/2016 5:17:36 AM: Plex Media Server has stopped!
12/15/2016 5:17:36 AM: PlexScriptHost Stopped.
12/15/2016 5:17:36 AM: Plex Media Scanner Stopped.
12/15/2016 5:17:59 AM: Plex Service Stopped
12/15/2016 5:17:59 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/15/2016 5:17:59 AM: Attempting to start Plex
12/15/2016 5:17:59 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/15/2016 5:17:59 AM: Plex Media Server Started.
12/15/2016 5:17:59 AM: Plex Service Started
12/15/2016 7:06:51 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/15/2016 7:06:51 AM: Attempting to start Plex
12/15/2016 7:06:51 AM: Plex Service Started
12/15/2016 7:06:51 AM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/15/2016 7:06:51 AM: Plex Media Server Started.
12/15/2016 5:41:09 PM: Plex Media Server has stopped!
12/15/2016 5:41:09 PM: PlexScriptHost Stopped.
12/15/2016 6:19:28 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/15/2016 6:19:28 PM: Attempting to start Plex
12/15/2016 6:19:28 PM: Plex Media Server version is 1.3.2.3112. Can use startup argument.
12/15/2016 6:19:28 PM: Plex Media Server Started.
12/15/2016 6:20:20 PM: Plex Media Server has stopped!
12/15/2016 6:20:20 PM: PlexScriptHost Stopped.
12/15/2016 6:22:13 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/15/2016 6:22:13 PM: Successfully removed auto start entry from registry
12/15/2016 6:22:13 PM: Plex Media Server already running in session 0.
12/16/2016 12:26:50 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
12/16/2016 12:26:50 PM: Attempting to start Plex
12/16/2016 12:26:50 PM: Plex Media Server version is 1.3.3.3148. Can use startup argument.
12/16/2016 12:26:50 PM: Plex Media Server Started.
12/16/2016 12:26:50 PM: Plex Service Started

**Comment by cjmurph** [comment]
The service version is in the about dialogue.

The logs show that the service is detecting the version of PMS as new enough and starting with the startup argument. So unless Plex have removed the argument from the latest version, it should be working fine.
You could try making a shortcut to start Plex with the -noninteractive argument within an active user session and see if it makes the tray icon regardless.

PmsMonitor.cs Line 261:

```
Version v = new Version(plexVersion);
Version minimumVersion = new Version("0.9.8.12");
if (v.CompareTo(minimumVersion) == -1)
{
  OnPlexStatusChange(this, new StatusChangeEventArgs(string.Format("Plex Media Server version is {0}. Cannot use startup argument.", plexVersion)));
}
else
{
  OnPlexStatusChange(this, new StatusChangeEventArgs(string.Format("Plex Media Server version is {0}. Can use startup argument.", plexVersion)));
  plexStartInfo.Arguments = "-noninteractive";
}
```

**Comment by seanvree** [comment]
@cjmurph ,

okay, so I just went into the windows service manager and added the -noninteractive to the start params of the PlexService properties.  Seems to work. 

How do I add that param permanently?  I have to stop the service add the param, then start it again, but when I stop it, it the param disappears?

**Comment by cjmurph** [comment]
The service doesn't take any arguments so it can't have done anything.

**Comment by seanvree** [comment]
humm, so what do you suggest @cjmurph ? the PMS is on a headless server, so I'm never logged on, hence the whole purpose of this service.

**Comment by cjmurph** [comment]
So, with your last comment, you said you weren't getting those errors in the pms logs anymore. have you tried just running the service again and checking the logs? are you sure those log entries are from when it's being run by this service? have you tried to get it running via a scheduled task, srvany etc where it could have generated those log entries? I'll update my pms today to the latest version and see if I get it, I'm still running 1.2.7.2987

**Comment by cjmurph** [comment]
I've updated and I have no mention of notifyicon in my pms logs. the noninteractive argument is still working.

**Comment by seanvree** [comment]
@cjmurph  I wasn't getting those errors if I stopped the service, added that argument to the actual PMS service in windows service properties.  But like you said, once I stop the service that argument goes away, and I'll start getting the errors again.

**Comment by cjmurph** [comment]
are you sure that's this software you're running from the services snap in? it doesn't even use any start parameters that are sent to it at startup. if you look at the service class [https://github.com/cjmurph/PmsService/blob/master/PlexService/PlexMediaServerService.cs](https://github.com/cjmurph/PmsService/blob/master/PlexService/PlexMediaServerService.cs) you'll see that the OnStartup method that is called when the service is started, never uses the args passed to it.
I imagine if you used something like srvany to create a service, it might do something, but even then I don't suspect it passes the parameters through. 
Have you ever tried any other method to get plex running as a service prior to this? is there any chance you left something behind?

**Comment by seanvree** [comment]
@cjmurph  

I'm not seeing the errors anymore, so I'll close. 

Thanks for the help!
