### ISSUE TITLE
Launche of Firefox

### ISSUE THREAD

**Issue by stanthewizzard** [cjmurph/PmsService#2]
Hello
Apparently the service launches Firefox ... and hangs 

O_o

**Comment by cjmurph** [comment]
Hi, I can't replicate this. At what stage does it do it? Start up?

**Comment by stanthewizzard** [comment]
Yes 
reboot of the computer I've got a dead firefox pointing to localhost plex

**Comment by cjmurph** [comment]
Well the service itself doesn't launch a browser, just Plex and any auxiliary applications you've setup.

Could be a setting within Plex to open a browser when it starts. Might want to look there. To reiterate, the service doesn't launch a browser instance itself ever. What session number is the firefox process running in?

**Comment by stanthewizzard** [comment]
Session ID 0

Where could I find such line in Plex

Thansk for help

**Comment by cjmurph** [comment]
A quick search of the plex forums and I found this:

https://forums.plex.tv/index.php/topic/55655-how-to-prevent-plex-server-from-opening-browser-window-on-startup/

Looks like it might be your issue.

Let me know if it solves the problem so I can close this. Also, I can adjust that registry entry when the service starts so I'm keen to know if this fixes the issue for you.

Thanks.

**Comment by stanthewizzard** [comment]
You rock
That was it
firstrun=0

:)

Huge Thanks

**Comment by cjmurph** [comment]
Awesome. Closed!
