### ISSUE TITLE
Build fails because PlexServiceInstaller dlls are blocked

### ISSUE THREAD

**Issue by xxbiohazrdxx** [cjmurph/PmsService#20]
Not really a code defect, but you might want to make note in the Readme to unblock the WixCommonUiExtension.dll when trying to build. It certainly would have saved me some time and headache.

Also consider distributing a prebuilt installer. Not everyone happens to have VS laying around.

**Comment by cjmurph** [comment]
Go to releases, you'll find the pre built installers there.
