### ISSUE TITLE
[Request] Add 4k (200% scaling) support

### ISSUE THREAD

**Issue by Hackmodford** [cjmurph/PmsService#21]
The tray icon is blurry on my 4k monitor and the menus pixelated. Is there a way to ad support for higher resolution monitors?

**Comment by cjmurph** [comment]
How are the settings windows when they're opened? What operating system are you using?

**Comment by Hackmodford** [comment]
I'm using Windows 10.

The settings window seems to be rendering correctly. But after opening it, if I try to open the context menu on the tray icon, it goes from being big and pixelated to being very tiny.

**Comment by cjmurph** [comment]
Ok, I don't have a 4k monitor to test on. A quick google suggests this is pretty common with most 3rd party apps and display scaling. I'll investigate how I can fix this, but it will take me a while as I'll need to source a monitor for testing.

**Comment by Hackmodford** [comment]
I believe, as a workaround, you could set your display settings to 200% scaling to test this issue.

**Comment by cjmurph** [comment]
Let me know how [1.1.2](https://github.com/cjmurph/PmsService/releases/tag/v1.1.2) works for you.

Thanks.

**Comment by Hackmodford** [comment]
Menu and icon is still pixelated. Now settings interface is lower res.
![screenshot 2017-06-11 14 49 44](https://user-images.githubusercontent.com/326668/27013636-5cdc32f2-4eb5-11e7-85e9-a14475147dba.png)

**Comment by cjmurph** [comment]
I guess this could be because the tray app is essentially a windows forms application launching wpf windows. I don't think microsoft has done anything to help forms apps handle dpi changes properly.

I'll investigate a rewrite purely in wpf and see if I can get on top of this. I'm away for work at the moment, but when I return home I'll get a 4k monitor and start testing.

**Comment by cjmurph** [comment]
Also, I notice in the screenshot, that all the third party apps have pixelated icons. (avira, powerchute, steam). Not to make an excuse but it's clearly an issue for everyone. makes me feel better about it at least :)

**Comment by Hackmodford** [comment]
On a side note, I found the lack of proper ui scaling to be disturbing when compared to macOS. Probably not much you can do about it :)

In any case, thanks for looking into it!

**Comment by Hackmodford** [comment]
For some reason, it seems to be working now. I don't know what could have changed.

I think we should blame it on Windows being Windows :P
