### ISSUE TITLE
Various Plex/Pms Service Issues

### ISSUE THREAD

**Issue by RHungerschafer** [cjmurph/PmsService#22]
After initially installing Plex then using AlwaysOn to run Plex as a service on a Windows 10 Pro x64 on a Dell PC it seemed to work fine for all and no login was required. Then after uninstalling AlwaysOn and removing it from the Registry and updating Plex Server with Plex-Media-Server-1.7.5.4035-313f93718.exe and adding PlexService_1.1.2.msi set to start automatically then started experiencing various issues. After troubleshooting these are the issues that remain:

    Plex Server only runs while I am logged in to the PC.
    FMoviesPlus: Error: List index out of range.
    SS-Plex: Conversion Failed. The transponder crashed or failed to start up.
    G2G.FM: Seems to be working properly
    BitTorrent: Folder “Recent” is always empty, otherwise working properly.
    Movies2K: Sorry. We couldn’t load requested content.

[Other Plex Details.zip](https://github.com/cjmurph/PmsService/files/1157442/Other.Plex.Details.zip)
[Plex Media Server Databases_2017-07-17_09-17-43.zip](https://github.com/cjmurph/PmsService/files/1157443/Plex.Media.Server.Databases_2017-07-17_09-17-43.zip)
[Plex Media Server Logs_2017-07-17_09-17-37.zip](https://github.com/cjmurph/PmsService/files/1157444/Plex.Media.Server.Logs_2017-07-17_09-17-37.zip)

**Comment by RHungerschafer** [comment]
A few more files that might help.
[com.plexapp.plugins.bittorrent.log.zip](https://github.com/cjmurph/PmsService/files/1157482/com.plexapp.plugins.bittorrent.log.zip)
[com.plexapp.plugins.fmoviesplus.log.zip](https://github.com/cjmurph/PmsService/files/1157484/com.plexapp.plugins.fmoviesplus.log.zip)
[com.plexapp.plugins.g2gfm.log.zip](https://github.com/cjmurph/PmsService/files/1157481/com.plexapp.plugins.g2gfm.log.zip)
[com.plexapp.plugins.movie2k.log.zip](https://github.com/cjmurph/PmsService/files/1157483/com.plexapp.plugins.movie2k.log.zip)
[com.plexapp.system.log.zip](https://github.com/cjmurph/PmsService/files/1157485/com.plexapp.system.log.zip)

**Comment by cjmurph** [comment]
When running as a service you must have all your sections configured in plex using unc paths. Have you done that? Mapped drives aren't available until a user session has been created.

**Comment by RHungerschafer** [comment]
Only found the two paths below and changed them to UNC as indicated.  So far everything seems to be working great.  Thank you very much for your assistance!

Server Settings
General
The path where local application data is stored
C:\Users\Robert\AppData\Local
\\localhost\c$\Users\Robert\AppData\Local
Scheduled Tasks
Backup directory
C:\Users\Robert\AppData\Local\Plex Media Server\Plug-in Support\Databases
\\localhost\c$\Robert\AppData\Local\Plex Media Server\Plug-in Support\Databases

**Comment by cjmurph** [comment]
Interesting, those shouldn't have mattered, they're not a network resource. Is the service running under the user account "Robert" or something else? If it's running as local system or some other user, that path won't be available purely from a permissions standpoint, so I guess it makes sense, not sure how making the path UNC would help though. 

I personally moved the Plex media server folder out of the user folder and put it at a machine wide accessible place in my case d:\plex as I didn't like that massive folder living in my user folder.

**Comment by RHungerschafer** [comment]
Yes the service is running under Robert, the only Administrative account on the computer.  As per your example I should have put the Plex media server folder in a common location.

Thanks.
