### ISSUE TITLE
[Request for help] Plex Media Server not running

### ISSUE THREAD

**Issue by mbmaniac** [cjmurph/PmsService#23]
I'm running Plex Media Server 1.7.5.4035 on a Windows Server 2016  Standard, Version 1607, OS Build 14393.1480 that I just rebuilt from scratch on a Dell PowerEdge T310 with 32GB RAM and 2-3TB SAS drives in a RAID 1 configuration. 

When I upgraded from Server 2003 to 2012 R2 and then to 2016 and I was able to use Plex Service. 

But after my new build, using Plex Service 1.1.2 closes Plex Media Server disabling a remote connection.

I hope you will be able to resolve this issue as I like you application very much. 

Please let me know if there is anything I can do to assist you.

**Comment by cjmurph** [comment]
Hi,
First. does plex run on it's own (when not using the service)?
Are you setting plex up from scratch or have you copied a backup of your library?

I'm confused by your statement "closes Plex Media Server disabling a remote connection."
Does it close plex OR does it disable remote connections? If the latter, are you saying you can access plex while logged in to the server? have you configured your firewall? have you ensured you are using UNC paths when creating your library sections in plex?

Sorry, lots of questions, but that's where you need to start looking.

Also, send the logs from the service (not plex logs)

Thanks.
