### ISSUE TITLE
Plex service crashing / Transcoding?

### ISSUE THREAD

**Issue by seanvree** [cjmurph/PmsService#24]
OS:  Windows 10E 1703 X64
PMS:  Version 1.8.1.4140 (preview)
PMS Service ver: 1.1.2.0

Hey @cjmurph , 

Been using your program for a couple years now, it's great man. 

First time i've been having some issues recently:

The service seems to crash about every 4 hours.  Now, I'm not sure if it's the service or PLEX, as there isn't really anything in the service logs (Below). But when it crashes, it DOES recover. 

I started to see this issue when I upgraded to the preview version to get the hardware transcoding. HW transcoding seems to be working great, but I'm not sure why PLEX is crashing?

I've been doing some research and it seems that other people are having the same issue on the prview build when using PLEX as a service:

http://forums.plex.tv/discussion/282812/hardware-transcoding-preview-issues-platform-windows/p2

https://forums.plex.tv/discussion/93994

Thoughts?

Here's the service logs:

```
9/8/2017 3:52:46 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 3:52:46 AM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 3:52:46 AM: Attempting to start Plex
9/8/2017 3:52:46 AM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 3:52:46 AM: Plex Media Server Started.
9/8/2017 3:52:46 AM: Plex Service Started
9/8/2017 4:08:08 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 4:08:08 AM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 4:08:08 AM: Attempting to start Plex
9/8/2017 4:08:08 AM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 4:08:08 AM: Plex Media Server Started.
9/8/2017 4:08:08 AM: Plex Service Started
9/8/2017 4:21:07 AM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 4:21:07 AM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 4:21:07 AM: Attempting to start Plex
9/8/2017 4:21:07 AM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 4:21:07 AM: Plex Media Server Started.
9/8/2017 4:21:07 AM: Plex Service Started
9/8/2017 6:33:35 PM: Plex Media Server has stopped!
9/8/2017 6:33:35 PM: Plex DLNA Server Stopped.
9/8/2017 6:33:35 PM: PlexScriptHost Stopped.
9/8/2017 6:33:35 PM: PlexTranscoder Stopped.
9/8/2017 6:33:35 PM: Waiting 200 seconds before re-starting the Plex process.
9/8/2017 6:36:55 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 6:36:55 PM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 6:36:55 PM: Attempting to start Plex
9/8/2017 6:36:55 PM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 6:36:55 PM: Plex Media Server Started.
9/8/2017 6:36:56 PM: Plex Service Stopped
9/8/2017 6:36:57 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 6:36:57 PM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 6:36:57 PM: Plex Media Server already running in session 0.
9/8/2017 6:36:58 PM: There is already a listener on IP endpoint 0.0.0.0:8787. This could happen if there is another application already listening on this endpoint or if you have multiple service endpoints in your service host with the same IP endpoint but with incompatible binding configurations.
9/8/2017 6:36:58 PM: Plex Service Started
9/8/2017 7:56:29 PM: Plex Media Server has stopped!
9/8/2017 7:56:29 PM: Plex DLNA Server Stopped.
9/8/2017 7:56:29 PM: PlexScriptHost Stopped.
9/8/2017 7:56:29 PM: Waiting 200 seconds before re-starting the Plex process.
9/8/2017 7:59:49 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 7:59:49 PM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 7:59:49 PM: Attempting to start Plex
9/8/2017 7:59:49 PM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 7:59:49 PM: Plex Media Server Started.
9/8/2017 9:20:25 PM: Plex Media Server has stopped!
9/8/2017 9:20:25 PM: Plex DLNA Server Stopped.
9/8/2017 9:20:25 PM: PlexScriptHost Stopped.
9/8/2017 9:20:26 PM: PlexTranscoder Stopped.
9/8/2017 9:20:26 PM: Waiting 200 seconds before re-starting the Plex process.
9/8/2017 9:23:46 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 9:23:46 PM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 9:23:46 PM: Attempting to start Plex
9/8/2017 9:23:46 PM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 9:23:46 PM: Plex Media Server Started.
9/8/2017 10:08:42 PM: Plex Media Server has stopped!
9/8/2017 10:08:42 PM: Waiting 200 seconds before re-starting the Plex process.
9/8/2017 10:09:28 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
9/8/2017 10:09:28 PM: Successfully set the 'FirstRun' registry key to 0
9/8/2017 10:09:28 PM: Plex Service Started
9/8/2017 10:09:28 PM: Attempting to start Plex
9/8/2017 10:09:28 PM: Plex Media Server version is 1.8.1.4140. Can use startup argument.
9/8/2017 10:09:28 PM: Plex Media Server Started.
```

Here's the PMS logs from that same period:

```
Sep 08 22:07:45 PLEX plex_media_server.log:  Sep 08, 2017 22:07:44.353 [43080] ERROR - Source image with format 25 and size 1x1, refusing to create strange sized thumbnail of size 1x1
Sep 08 22:07:45 PLEX plex_media_server.log:  Sep 08, 2017 22:07:44.353 [43080] ERROR - Error resizing an image, we don't trust what we cached [C:\plex\Plex Media Server\Cache\PhotoTranscoder\83\8307a057630cb98b84998945bbe9a94f1a920f80.jpg]
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.290 [26856] INFO - Plex Media Server v1.8.1.4140-82ea538ca - Microsoft PC x64 - build: windows-i386 english - GMT -07:00
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.290 [26856] INFO - Windows version: 10.0 (Build 15063), language en-US
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.290 [26856] INFO - 8 4008 MHz processor(s): Architecture=0, Level=6, Revision=24067 Processor Identifier=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.346 [30692] INFO - Starting in noninteractive mode
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.352 [30692] INFO - SQLITE3:5096C505, 283, recovered 986 frames from WAL file C:\plex\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.db-wal
Sep 08 22:09:29 PLEX plex_media_server.log:  Sep 08, 2017 22:09:28.395 [30692] INFO - SQLITE3:5096C505, 283, recovered 642 frames from WAL file C:\plex\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.blobs.db-wal
Sep 08 22:09:30 PLEX plex_media_server.log:  Sep 08, 2017 22:09:29.080 [13632] INFO - Successfully retrieved OCSP response
Sep 08 22:09:30 PLEX plex_media_server.log:  Sep 08, 2017 22:09:29.088 [38816] INFO - Successfully retrieved OCSP response
Sep 08 22:09:32 PLEX plex_media_server.log:  Sep 08, 2017 22:09:30.655 [38528] ERROR - LPE: unknown item 173484.
Sep 08 22:09:32 PLEX plex_media_server.log:  Sep 08, 2017 22:09:30.655 [38528] ERROR - Versions: failed to generate query for path library://4cf5e528-ca6d-4cd5-872b-3c84020cf5b8/item/%2Flibrary%2Fmetadata%2F173484
```

**Comment by cjmurph** [comment]
The service logs show plex is crashing. its likely that the hardware acceleration requires some resource/process/service that isn't available without a user session.

The PMS logs don't seem to suggest much to me, can you maybe post a little more of the PMS log.

I haven't actually updated my own pms for quite some time so I'm a bit out of the loop with this new functionality. I'll update now and see what I can see.

**Comment by seanvree** [comment]
@cjmurph  - 

Appreciate the response, Sir. 

Yeah, I'll do some more testing and try to get you some debug logs.  It's strange because the transcoding works really great when it's working.   And the few times it's crashed, and I can't pin it down as to why?  A couple times it crashed with NO streams playing at all.  But like I said, some other dudes were having issues only when it was run as service.  So...I'll keep an eye on it, and let you know.

**Comment by seanvree** [comment]
@cjmurph  - 

Are you familare with NSSM?

So, just as some testing, I've been using it and haven't had any crashes, and hardware transcoding is working.  Not sure if that helps you at all.

**Comment by cjmurph** [comment]
Yeah I know it. I can't see any reason for it to behave differently. Are you sure it's not crashing and just recovering? Are you using any special arguments with the service you made using nssm? One thing you can try with PMS as a service is to add explorer.exe as an auxillary application and see if that has an effect.

**Comment by seanvree** [comment]
@cjmurph  - you mean is it crashing when running on NSSM?  If so, no it's not.

**Comment by cjmurph** [comment]
did you create the service with nssm with the no interactive command line argument?

I wonder if there's something the plex team have missed there...

**Comment by seanvree** [comment]
I didn't actually know about that argument until I was getting the icon notifications warnings, so I added the arg now, but it was running fine without it for 48 hours and no crashes.

**Comment by seanvree** [comment]
@cjmurph  - 

You look into this at all?  

I've been running with NSSM and haven't had any crashes.

**Comment by cjmurph** [comment]
No, my server doesn't have the hardware to test it. I was actually waiting on more feedback K from you to see if it crashed once you added the startup argument. Also, I mentioned to maybe try adding explorer.exe as an aux application to see if that had an effect.

**Comment by seanvree** [comment]
@cjmurph, I can do that.  However, before I switch back to PMS service - a couple questions:

currently, PLEX with NSSM under the local system account w/ arg -noninteractive

1 - When I was running with PMS service, it WAS running under the .administrator account, however, the plex data directory WAS/IS c:\plex.  - so can I change the account on PMS Service to Local System before  I restart the PMS Service again? Nothing should change since the data was stored in C:\plex, right?

2 - As far as changing the startup args for PMS Service, should I add the -noninteractive arg and/or add the explorer.exe as an aux application? (I'm assuming should do that via Windows Services?)

Thx,

**Comment by cjmurph** [comment]
For 1, yep it'll work fine.

For 2, there are no startup args for the service. It checks the installed PMS version and uses the startup argument if PMS is the correct version. 

Maybe first just try the account change and see if it behaves any different.

**Comment by seanvree** [comment]
@cjmurph  

2) - I meant, adding it in manually to the service seeings via the win GUI:

![image](https://user-images.githubusercontent.com/8906637/30360747-ffbb6740-9807-11e7-937c-45092bf1620a.png)

**Comment by cjmurph** [comment]
I know what you mean, but those are arguments for the service and it doesn't take any.

**Comment by seanvree** [comment]
@cjmurph  got it.  I'll give 'er a go and report back.

**Comment by seanvree** [comment]
@cjmurph 

wanted to give an update. 

looks like the PMS has not crashed since changing the service account to local SYSTEM and adding explorer.exe as an aux application. 

Not sure if this helps you at all.

**Comment by cjmurph** [comment]
Great, thanks for testing that. I wonder which of those two it was.

would you mind removing the aux application and see if it works?

thanks.

**Comment by seanvree** [comment]
@cjmurph will do.

**Comment by seanvree** [comment]
@cjmurph 

Haven't had any crashes yet.  So I'm not sure what it was?

**Comment by seanvree** [comment]
@cjmurph  not sure if this is related, but been having issues again.  Posted over on the plex forums:

https://forums.plex.tv/discussion/93994/pms-as-a-service/p41


OS:  Windows 10E 1709 X64
PMS:  1.9.6.4385 


I started getting these errors too. Not sure if it was the Windows Fall CU 1709 that started or a recent PLEX update.  However, seems that PLEX crashes about once a day as well .  I tried running the service wrapper as SYSTEM and Administrator, but I get the same errors on both accounts. 



```
10/28/2017 12:41:39 PM: Plex Media Server has stopped!
10/28/2017 12:41:39 PM: Plex DLNA Server Stopped.
10/28/2017 12:41:39 PM: PlexScriptHost Stopped.
10/28/2017 12:41:39 PM: PlexTranscoder Stopped.
10/28/2017 12:41:39 PM: Plex Tuner Service Stopped.
10/28/2017 12:41:39 PM: Waiting 300 seconds before re-starting the Plex process.
10/28/2017 12:46:39 PM: Plex executable found at C:\Program Files (x86)\Plex\Plex Media Server\Plex Media Server.exe
10/28/2017 12:46:39 PM: Successfully set the 'FirstRun' registry key to 0
10/28/2017 12:46:39 PM: Attempting to start Plex
10/28/2017 12:46:39 PM: Plex Media Server version is 1.9.6.4385. Can use startup argument.
10/28/2017 12:46:39 PM: Plex Media Server Started.
```
```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user NT AUTHORITY\SYSTEM SID (S-1-5-18) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

**Comment by cjmurph** [comment]
Ok, so back to the message prior to this, did we determine that it was changing the user to LOCAL SYSTEM that fixed the previous issue? 
Once you removed the aux app, it still ran fine under LOCAL SYSTEM?

Does plex run when you run it normally (not as a service)?

A quick google shows the dcom error is pretty common.
here's a link to a technet question that might help you resolve it.
[https://social.technet.microsoft.com/Forums/ie/en-US/dfc465bc-7bbd-483e-b98b-2ba56fa98313/the-applicationspecific-permission-settings-do-not-grant-local-launch-permission-for-the-com-server?forum=configmgrgeneral](url)

**Comment by seanvree** [comment]
@cjmurph , 

Well, I don't think it was conclusive that changing it to local system is what fixed it.  Also, I was NOT having the DCOM error till recently.  I know DCOM errors are fairly common, but I'm getting these logs like every 10 seconds. which is not common. 

Yes, PLEX runs find when not as a service.  


Also, that link didn't work.

**Comment by moblaw** [comment]
I have the same issue as OP

"9/8/2017 9:20:25 PM: PlexScriptHost Stopped.
9/8/2017 9:20:26 PM: PlexTranscoder Stopped."

**Comment by cjmurph** [comment]
Any updates on this? Is it resolved with newer builds of plex?

**Comment by moblaw** [comment]
I Think so I have not encountered it in a month.


Sendt fra min Samsung Galaxy-smartphone.
-------- Oprindelig besked --------Fra: cjmurph <notifications@github.com> Dato: 16/02/2018  23.15  (GMT+01:00) Til: cjmurph/PmsService <PmsService@noreply.github.com> Cc: moblaw <moblawski@gmail.com>, Comment <comment@noreply.github.com> Emne: Re: [cjmurph/PmsService] Plex service crashing / Transcoding? (#24) 
Any updates on this? Is it resolved with newer builds of plex?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cjmurph/PmsService","title":"cjmurph/PmsService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cjmurph/PmsService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cjmurph in #24: Any updates on this? Is it resolved with newer builds of plex?"}],"action":{"name":"View Issue","url":"https://github.com/cjmurph/PmsService/issues/24#issuecomment-366374093"}}}

**Comment by seanvree** [comment]
haven't seen this issue in a while.  Closing
