### ISSUE TITLE
Media "Not Available" When started by PMS Service

### ISSUE THREAD

**Issue by LindsayCole** [cjmurph/PmsService#25]
Heya, I get "Not Available" on all media inside Plex, when PMS Service starts the Plex Server. Does not happen when I manually start the Plex server.

Media is on a dedicated Windows File Server, credentials are entered properly into PMS Service. I reinstalled, and same problem exists. Any idea how to troubleshoot?

Thanks,

**Comment by cjmurph** [comment]
Are you using mapped drives? You need to use unc paths when it's run as a service.

**Comment by LindsayCole** [comment]
I do use Mapped Drives.

Crap, thats an issue. I have a rather large library. In my experience, Plex doesn't take kindly to changing library paths. (A rescan takes around 6-7 days for my entire library.)

**Comment by cjmurph** [comment]
Yeah, it kinda sucks sorry. Not much you can do about it. The mappings only happen once a user session is created.
