### ISSUE TITLE
Solution for mapped drives?

### ISSUE THREAD

**Issue by devcompl** [cjmurph/PmsService#27]
According to some threads I found, like [this one](https://stackoverflow.com/a/182846), its possible use a mapped drive if the service mapps the drive itself, or if another service running as the same user maps the drive first.
We could add settings for mapped drives (path, username, password, drive letter) to the tray options, and the service would map the drives in OnStart method.
As far as I can tell it should work.

There is a [network drive api](https://www.codeproject.com/Articles/6847/Map-Network-Drive-API) we could possibly use.

**Comment by cjmurph** [comment]
Hi, I actually don't see this as an issue that needs solving. UNC paths work perfectly.

**Comment by devcompl** [comment]
Well they do. But they require full library refresh which i bet many users would like to avoid, while you can easily change mapped drive path in seconds. 

Adding mapped drive support would also make pmsservice more transparent. You just install and configure it and you dont have to change anything in your plex server.

Also if you ever move your data to a new server you would need to change unc paths and refresh again.

I think this is worth considering.

**Comment by cjmurph** [comment]
Yeah, that's valid. I'll look at it when I get a chance.

**Comment by devcompl** [comment]
I see you have added drive mapping support.
But it seems there is no way to set the username and password for the share?

Tried using "Credential Manager" but I bet those passwords are not available for the service.

**Comment by cjmurph** [comment]
I chose to avoid it to try and simplify as much as possible. Just make sure that the user account the service is run as, has access to the share. (check your share permissions). The same is true if you use a unc path with plex. The account plex media server is run as needs to have permission to access the share.

**Comment by devcompl** [comment]
Yes that will work but I dont think this is a good solution because it is some what limiting. You just cant predict user setups so its best to allow for flexibility where it is feasible.

I tried to do it like you said, but in my case I had to create another user on the plex server system to match the user for the mapped drive, so I had to migrate plex settings and registry and I could not get the webui to work. But the logs indicated that the drive mapping was successful.

**Comment by cjmurph** [comment]
Surely you could have just added the existing plex user account to the share permissions and saved all that hassle.

I'll look at it in the next version, it's not difficult to add. 

My preference is that this should be handled by the user at the share permission level.

**Comment by jeramie72** [comment]
i'm running v 1.1.2.0 because its been fine for me. but now i'm experimenting with adding a mapped rclone cache drive (z:) and when i run plex as a service via pmsservice, it can't see the z: drive.  if i run plex normally it sees it fine.  i've made sure that pmsservice is running as the same user as my rclone mount but that didn't seem to help. do you by chance have any ideas? will try to update to the latest pmsservice to see if that helps at all.

**Comment by cjmurph** [comment]
Mappings are not created until the user session is created. Services run in session 0, the are no mapped drives.

I've added the functionality to have this service create the mapping, it seems to work. Grab the latest version and try it.

**Comment by jeramie72** [comment]
hmm yea i installed the latest but unfortunately i don't see a way to map an rclone remote via a UNC path, else i've read i could actually just add the UNC path in plex and it would see it ok.  i'm using rclone to map my google drive if that helps at all.  this isn't really a pmsservice issue, i was just hoping there might be a work around that you guys knew about.

**Comment by jeramie72** [comment]
yea i tried auxillary app as well, it ran it but didn't pop up the command window like normal and the drive letter never showed up unfortunately.  i tried with the arguments added to the arguments box and also with " " around a complete command line in the app box but show the process running but no drive ever appears. where-as the same command line ran at a prompt pops a drive up.

**Comment by cjmurph** [comment]
It can't pop up the command window, it's running in a different session, that session has no desktop. Also, the working directory will need to be set correctly

**Comment by jeramie72** [comment]
gotcha that makes sense. yea the working directory was the same as where the executable was at.  would maybe the fact that its running it in a different session cause the drive letter to not appear for my session?

**Comment by cjmurph** [comment]
Yep, but it may be available for Plex to use at that point, did you try Plex?

**Comment by jeramie72** [comment]
hmmm no i sure didn't, let me try that and i'll let you know

**Comment by jeramie72** [comment]
lol yup, plex sees it fine! thanks man, much appreciated.
So for anyone who might search this in the future. i put all the arguments in the argument box. saved, stopped the plex service, started the plex service.  went into add folder for a library in plexweb and Z: is there even tho my computer doesn't show a Z.

**Comment by jeramie72** [comment]
so any magical way you can think of for me to be able to access that Z: drive from my desktop?

**Comment by cjmurph** [comment]
Nope, it's not available to you. I. The same way that if another user was running it you couldn't access it. You'd have to run a seperate mount. I'm not familiar with the program so I can't really comment further

**Comment by cjmurph** [comment]
I'm closing this issue as the mounting works. Currently my preference is to manage credentials at the share level, ie, add the account the service is run as to the share permissions, rather than use separate account details when connecting to map.
