### ISSUE TITLE
Ability to change login from the service menu

### ISSUE THREAD

**Issue by rguilmette** [cjmurph/PmsService#28]
If I change my login password the service disconnects. It would be nice to have the ability to change the password within the right click menu. Right now I have to uninstall the service then reinstall to renter the credentials.

**Comment by cjmurph** [comment]
You can change the credentials in the services snap in within windows, no need to reinstall. 
Just hit start then type services.msc. find the service, right click properties and change the account the service runs as.

If I add this to the tray application it would need to be run with administrator credentials and I know that would be a problem for many users.

Hope that helps.

**Comment by rguilmette** [comment]
Ok, thanks!

--------------------------
There are 10 types of people, those who understand binary and those who don't.
