### ISSUE TITLE
Cannot Execute Non .exe files

### ISSUE THREAD

**Issue by DWSR** [cjmurph/PmsService#3]
Hi there,

I have Python installed and I'm running CouchPotato from git. If I point PmsService to a .py file, it won't execute it, claiming "2015-06-09 4:01:29 PM: CouchPotato failed to start. The specified executable is not a valid application for this OS platform.". Python script files are properly associated with the interpreter so I assume this is a hardcoded limitation. Any way that we can get support for this?

**Comment by pinki** [comment]
Hi,
you could say that python.exe is the executable and give the path to your .py file as argument.

**Comment by cjmurph** [comment]
Hi DWSR,

as pinki said, you would need to execute python and supply the script as an argument. I think I tried both ways when I was testing and found the current implementation offers more flexibility than just calling for the system to execute anything and be damned the result.

Let me know if it executes properly when you do it as an argument and I'll close the issue.

**Comment by DWSR** [comment]
It doesn't because the working directory isn't set properly (I would expect it's set to wherever Python.exe is, rather than the script dir). I could write a launch script or something else from there, but this issue seems like it would be much easier to solve on the launching side. Would it be possible to add the ability to specify the working directory, much like Windows shortcuts?

**Comment by cjmurph** [comment]
I've added the ability to specify the working directory with release 1.1.0. let me know how you go.

**Comment by DWSR** [comment]
Everything now seems to be working as intended. You can close this, thank you so much!

**Comment by cjmurph** [comment]
no worries
