### ISSUE TITLE
PlexPY fails to start

### ISSUE THREAD

**Issue by kravena** [cjmurph/PmsService#30]
PlexPY is failing to start with error as an auxillary app, when it starts fine from the command line 👍 

27/01/2018 00:05:39: Attempting to start Plexpy
27/01/2018 00:05:39: Plexpy failed to start. The specified executable is not a valid application for this OS platform.

PlexPY is a python app.

Any ideas ?

**Comment by cjmurph** [comment]
Can you share a screenshot of the aux app configuration please

**Comment by kravena** [comment]
attached.

![plexpy](https://user-images.githubusercontent.com/16151488/35466367-25d5bd0a-02fb-11e8-8f45-baffa7e1e86b.png)

Note I have a junction 👍 
13/11/2015  12:46    <JUNCTION>     Plex Media Server [d:\Plex Media Server]

But this should have no relevance.

**Comment by cjmurph** [comment]
You need to call the python executable with the plexpy script as an argument. 
Under your login, there is an association of .py files to the python executable, so double clicking the py file will work. You need to do it explicitly in this situation.

**Comment by cjmurph** [comment]
@kravena did you get this working?

**Comment by cjmurph** [comment]
@kravena in the other issue you raised a year ago #17 another user posted a screenshot of their plxpy configuration. did you see that. it looked like this:
![plexpy](https://user-images.githubusercontent.com/2868949/36331972-1b3f4558-13ab-11e8-9b1d-45d4f2be03e8.png)

**Comment by cjmurph** [comment]
I can only assume this is resolved. closing.
