### ISSUE TITLE
All media becomes unavailable when app restarts plex. 

### ISSUE THREAD

**Issue by morpheus2n2** [cjmurph/PmsService#31]
For some reason if Plex randomly crashes or if I choose to stop it. When the wrapper restarts Plex as a service all my media becomes Unavailable.
But if I stop the service that had just been started then manually open plex everything works as intended.

I would love to keep this app but at the mo, I can't as plex refuses to work if started via said app.

**Comment by cjmurph** [comment]
Hi, can you please try and explain the issue more clearly and include some information about your configuration.

You say Plex refuses to work at all when run as a service, but also that it doesn't work after it crashes or is stopped, which implies it did work at first. Please clarify.

Where is your media stored? When you say stop the service, are you stopping Plex via the tray application or stopping the service via the services snap in?

Have you checked your logs?

**Comment by morpheus2n2** [comment]
Sorry.
When I use plex without this app it runs fine with no issues, but if I start using this app to do things like bring plex back after a crash etc, then All media is listed as Unavailable.

I have to stop both Plex and the wrapper via Task manager then load the Plex serve again manually for everything to work again as intended.

My media is Part NAS and Part local, in my current state I do not have the PMS wrapper running and everything is working as it should with all media available.

The moment I let the wrapper take over the launching of Plex is when things start playing up.

**Comment by cjmurph** [comment]
Do you have your Plex sections setup to use mapped drives or using unc paths? Mapped drives are not available to the service.

Do you use the same user for the service as when you run it normally?

**Comment by morpheus2n2** [comment]
You know what, now you said that it just clicked as to why its not working lol.

Yeah it will be due to plex using Mapped drives instead of UNC lol

So If I switch the locations out for UNC it should work fine?

**Comment by cjmurph** [comment]
you can go to unc paths
OR
the most recent version allows you to add mapped drives. the service will create the mapping when it starts plex.
