### ISSUE TITLE
unable to connect to service. check settings

### ISSUE THREAD

**Issue by zigfire66** [cjmurph/PmsService#37]
I have been using the plex media server service for a while. I had to install Norton Anti virus on my server to fix a plex crashing issue. After the install I began getting this message. The settings and port are set to the internal IP address and port. Should they be set to the public IP? Any suggestions would be appreciated.

**Comment by cjmurph** [comment]
Hi, what is giving you this message, the tray application? Is Plex running ok?

**Comment by cjmurph** [comment]
Check your firewall and make sure there's an exception for that port

**Comment by zigfire66** [comment]
Where can I find the file so I can just reinstall it? I'm tired of messing with this. Everything has been checked three times.

**Comment by ianandersonia** [comment]
I also have this issue with 1.1.7.  The tray icon fro plex media service says unable to connect to service. Check settings.  Cannot stop or start the service from the tray as options dont appear.

**Comment by zigfire66** [comment]
Is there a location that I can find this program? Found a file that was missing PlexService_1.1.1.msi and it said it should have been in my downloads folder. So I can't even uninstall it. Thanks

**Comment by zigfire66** [comment]
I can't even remove the old program because its asking for PlexService_1.1.1msi. Why would it be asking for the original file when the program is on 1.1.7? Better yet where can I find this so I can fix the problem.

**Comment by cjmurph** [comment]
Very odd, sorry for the trouble. I'm not sure how it could happen, but I think I might have changed the guid format in the Wix installer definition around the version.

The application is stored in program files (in the x86 folder on a 64 bit machine) if you manually delete the files, you'll need to clean up the registry yourself too or you still won't be able to reinstall.

Alternatively, you could download the version it's asking for from the releases page here and give it what it wants.

Good luck.
