### ISSUE TITLE
UNC path not allowing periods?

### ISSUE THREAD

**Issue by jobrien2001** [cjmurph/PmsService#38]
Trying to enter "\\tower\media.movies"  and I get a red tooltip and unable to save.

I can access the share just fine from the explorer.

**Comment by cjmurph** [comment]
That will be the regex I'm using. You can manually edit the setting file with the proper path and restart the service for now. I'll leave this open until I fix it.

Thanks.

**Comment by d8ahazard** [comment]
@cjmurph, @jobrien2001 - Fixed this as well.

https://github.com/d8ahazard/PmsService/commit/85cf1d38729848cedb0311243e7ad01c67eabea3
