### ISSUE TITLE
PMS Service disconnects and connects Plex Media server

### ISSUE THREAD

**Issue by itzcoatl13** [cjmurph/PmsService#43]
Hi,
When my computer restarts, the PMS Service starts the Plex Server but then it stops it. If I have the auto reconnect enabled, it will restart the PMS, but then stop it again, and it continues this loop. If I manually start the PMS, it stops looping. Anyone else seen this issue.

**Comment by cjmurph** [comment]
The service won't stop Plex without a command to do so. It will attempt to restart Plex if it crashes. 

You should check the Plex media server logs (not the service logs) when it's looping. Plex is crashing for some reason. I would guess it's permissions that aren't right somewhere.

**Comment by itzcoatl13** [comment]
I will check the Plex Media Server logs, but without the Plex Service and with auto start when login is enabled, everything works fine; the only thing is that I have to login.
