### ISSUE TITLE
Warning — Shell_NotifyIcon(NIM_ADD) failed: 0x80004005

### ISSUE THREAD

**Issue by robross0606** [cjmurph/PmsService#44]
Plex Log is being spammed with `Warning — Shell_NotifyIcon(NIM_ADD) failed: 0x80004005` On Windows 10 when running with PmsService with latest release (1.16.5.1488) of Plex.

**Comment by cjmurph** [comment]
What's the issue exactly?

**Comment by robross0606** [comment]
Sorry, ticket submitted somehow before i could type anything.

**Comment by cjmurph** [comment]
Which log? I run the service on windows 10 and I don't have this issue.

**Comment by cjmurph** [comment]
My Plex version is a slightly newer build, 1.16.5.1554, I wonder if the no interactive flag isn't working on 1488

**Comment by robross0606** [comment]
I see it on the live log in the web admin console.  I’m on Plex Pass  Wonder why my build is older. I tried to update and it says I’m on the latest.

**Comment by jstevenson72** [comment]
You need to select Beta channel.

**Comment by SpyderZT** [comment]
I think that ya'll and this guy should probably talk. :P

https://github.com/TechieGuy12/PlexServerAutoUpdater/
