### ISSUE TITLE
Network Shares Fail To Mount Before PMS Startup on Windows 11

### ISSUE THREAD

**Issue by d8ahazard** [cjmurph/PmsService#47]
A bit of a mouthful...but the title says it all.

On Windows 11, it appears as if *something* happens on startup where mapped drives don't mount before PMS starts up.

Logging in, manually stopping Plex, and then restarting it fixes.

Will fork and see if I can submit a PR to fix.

**Comment by cjmurph** [comment]
Thanks, maybe try setting the service startup to delayed, there might be some other service it depends on that isn't up in time on win 11

**Comment by xpusostomos** [comment]
This can happen... especially on external disk arrays that might have self healing and self repairing startups that take time to run before they can be mounted. Somebody really needs to look at the code and change it to try, wait a little while and then try again.. and again and again, until it comes up. I'd like to find time to look at the code to do it... so if @d8ahazard you're going to take a look, I welcome that.

**Comment by d8ahazard** [comment]
Closed, fixed with #50.
