### ISSUE TITLE
PMS not acknowledging viewed stuff

### ISSUE THREAD

**Issue by roughnecks** [cjmurph/PmsService#48]
Hello,
I have PMS installed on my Windows user account.

Every morning my father turns on the PC without logging in and starts watching stuff on his TV.. The problem is that PMS doesn't mark those vids as already watched, so when I login to my Windows user and access PLEX interface, it's not synced with what he's previously watched on TV.

Are we doing something wrong or is this a bug?

Thanks

**Comment by cjmurph** [comment]
Is the service running under the same account you're logging in with?
Make sure Plex isn't starting a second instance in your user session when you log in.

**Comment by roughnecks** [comment]
> Is the service running under the same account you're logging in with?

Yes, it is.

> Make sure Plex isn't starting a second instance in your user session when you log in.

This is what I see in Task Manager: https://i.imgur.com/gcFJ30N.jpeg https://i.imgur.com/RW2GJKU.jpeg
Also, I don't see anything else apart "PlexServiceTray" in the startup tab.

**Comment by cjmurph** [comment]
If you don't run it as a service, does it work as expected?

**Comment by roughnecks** [comment]
Oh, wait, I just remembered a thing about this.

Yesterday I deleted some old "Chrome" authorized devices and this morning it asked me to login again.. Could that be the issue?

**Comment by roughnecks** [comment]
> If you don't run it as a service, does it work as expected?

I have installed your service only a few days ago when I got a Mi Tv Stick for my TV.

**Comment by cjmurph** [comment]
I'd suggest heading to the Plex forums and asking the question there, it's not been a problem I've seen with the service, someone there may have experienced it before.

**Comment by roughnecks** [comment]
OK, will check it out tomorrow if it was just that login issue, as I said before, otherwise report it to PLEX forum.

Thanks
