### ISSUE TITLE
[Feature Request] Allow interface to be specified in Settings.json

### ISSUE THREAD

**Issue by Ancillas** [cjmurph/PmsService#5]
I'd like to be able to control the interface that PlexService binds to.  Right now it's listening on 0.0.0.0, and I'd like it to listen on 127.0.0.1.

**Comment by Ancillas** [comment]
Perhaps this is a bug and not a feature request?  I tried setting ServerAddress in Settings.json, but it won't accept my IP because it's "not a valid number".

I then used the tray app, clicked on connection settings, and saw that the address there was set to localhost, but even after a restart, it listens on 0.0.0.0.

I'm not confident this isn't user error, so I'll keep double checking myself.

**Comment by cjmurph** [comment]
OK, I just need a little clarification.

There are two settings files. one for the server and one for the tray application.

the tray application settings are simply the server address and port.

the server settings are everything else including port, but not the interface it listens on. 
I would have to go looking, but I'm pretty sure I set it to listen on all interfaces.

What is it exactly you want to change?

**Comment by Ancillas** [comment]
I want to be able to configure the server to only listen on localhost so
that it doesn't accept incoming connections from other machines on the
network.

**Comment by cjmurph** [comment]
Ok, well, it's designed to accept connections from other machines. You can pretty easily make a firewall rule to block port 8787. can you try that and see if it suits?

**Comment by Ancillas** [comment]
Yeah, that'll work fine if building the feature isn't work the time.
Thanks.
