### ISSUE TITLE
Complete Overhaul

### ISSUE THREAD

**Issue by d8ahazard** [cjmurph/PmsService#50]
Hey there, @cjmurph!

So, I did a thing...

As you can see from PR #49, I added some functionality to fix my issue #47 where shares weren't mounting properly on Windows 11 reboot.

But, that PR was created after I'd only been looking at the code for a few hours, so I missed a few key bits to make the settings actually stick. I also found that while the code worked fine, it didn't actually fix my problem, as I needed to wait a bit longer between remount attempts.

Which means I added another parameter to specify how long to sleep between remount attempts. And with the combination of "# of remount attempt" and "remount delay" params, my stuff now just mounts properly on reboots.

But, I didn't stop there. I bumped the dotnet version to 4.7.2 across the board...updated the support nuget packages...and updated all the language-level stuff to the latest major c# version. This means a bunch of code cleanup to use all the fun new features, as well as other fixes my IDE was yelling at me about (nested IF statements, unnecessary casts, typos).

Did I stop there? LOL...no. I also added a param to tell it to *not* start Plex if mounting fails (avoid issues with auto-emptying of trash), and then...uh...themes using the MahApp library. XD 

![image](https://user-images.githubusercontent.com/1633844/145048012-f2d9af59-550e-41f4-affb-ac61fa61c908.png)

![image](https://user-images.githubusercontent.com/1633844/145048170-7b6b2dce-6a47-442f-8302-3a3be061c8e5.png)

![image](https://user-images.githubusercontent.com/1633844/145048261-0aef5306-369b-46bc-b0a5-898a172bede2.png)

![image](https://user-images.githubusercontent.com/1633844/145048399-408e4154-6b5a-4853-ae49-dfd773e32679.png)

![image](https://user-images.githubusercontent.com/1633844/145048547-ddd8ff71-3ecb-4c95-91ef-5d9f60806c9b.png)

The side effect to this was a few things:

You can now read the "about" section, as mentioned in #46.
I added a copy of the app icon that's a tad smaller so it looks "right" in the app bars.
I made the bar titles "uniform", in that previously, I think 1/3 windows had a title in addition to the header, one didn't. So, I removed the title from the "about" window so none of them have titles.
While debugging things - I made the LogWriter a part of the common library so it can be accessed anywhere in the app(s)...and also possibly by the method used to launch Auxiliary apps as mentioned in #42. I also impulsively renamed the log file to "PlexService.log", because my log viewer app will just open it then. :P 
I simplified the serialization/deserialization of the settings file...modern JsonConverter has no issues taking the data in and out without any custom handler. (Was debugging why Theme wouldn't save, did this...eventually realized it was because I was only re-building the tray app, and not the full service bits)

So - I apologize for just kinda doing all this without any prior discussion. I don't want to create the impression that I'm trying to take this project over or anything...because that's definitely not the case, and I've got plenty of other things to be working on. But, I've used this app for a long time now, and thought, "Hey, I could probably show this thing a bit of love...not just for myself, but the whole community.". 

And, as it kinda snowballed past the scope of what I originally started trying to do, I figured the best recourse would be to just reach out here and say "Hey...I did a thing!". So, yeah...hey! :P

As I mentioned, I still want to look at the logging bit a little for aux apps, but everything I've done so far has been pushed here:

https://github.com/d8ahazard/pmsservice/tree/Overhaul

Ideally, I'd love to see this merged into the main project and out of my hands...just didn't want to submit one big messy PR to cover all of this. Let's discuss!

**Comment by d8ahazard** [comment]
Update: Added support for issue #42. Aux apps now have an option to "log output", which, when enabled, will tell the _auxProcess to redirect sdOut/sdErr data to the log file.

**Comment by d8ahazard** [comment]
And for testing/sanity purposes, I've dropped a release here:

https://github.com/d8ahazard/PmsService/releases/tag/v1.1.8

Nothing official, just wanted to make it easy for anybody else aside from me to give it a go and LMK if I broke anything.

**Comment by xpusostomos** [comment]
Wow, great work

**Comment by cjmurph** [comment]
Hi @d8ahazard 

Thanks heaps for jumping in and doing some work on this. I wrote it so long ago, it makes me cringe whenever I look at it hahaha.
It definitely needs some love and I appreciate you doing it. I'm really busy with work at the moment and I want to give your change the attention it deserves, so as soon as I can, I'll go through your pull request. 
I'm messaging to let you know I've seen it, I'm keen to look at it, but I'm a bit time poor ATM. I hope you can understand. Hopefully I can get to it in the next week or so.

**Comment by d8ahazard** [comment]
> Hi @d8ahazard
> 
> Thanks heaps for jumping in and doing some work on this. I wrote it so long ago, it makes me cringe whenever I look at it hahaha. It definitely needs some love and I appreciate you doing it. I'm really busy with work at the moment and I want to give your change the attention it deserves, so as soon as I can, I'll go through your pull request. I'm messaging to let you know I've seen it, I'm keen to look at it, but I'm a bit time poor ATM. I hope you can understand. Hopefully I can get to it in the next week or so.

Hey Chris! Glad to see you're still around! :D 

Just wanted to point out that the PR I submitted does not currently encompass all of the changes made at this point. As I went so far off the deep end, everything is in the "Overhaul" branch I created.

What was your thought on the other existing PR - the slightly more "flat" icon? I almost took the bmp and converted it to an .ico, but figured I'd ask your opinion first. Personally, I think it'd probably be a nice addition.

Also, the overhaul branch now contains fixes for what I think should be almost every open issue on the tracker, including PMS Updates, params for cmdline install, and logging of Aux apps. 

Last but not least, I just made a few more small fixes and tweaks today - implemented "Serilog" and a custom enricher I created for another project that helps show the calling file/method for log messages, etc. I also re-organized the tray context menu a bit, added a dark theme there, and made it so the "View log" bit just tells the shell to open the log file, versus trying to read it and then send that to notepad (which doesn't work with the new beta NP in win11). Plus some other minor fixes.


Point is, you'll definitely want to look at the branch I created. Lots of goodies in there. And no rush on your end, I'm just glad we were able to connect. :D

**Comment by cjmurph** [comment]
>
 and made it so the "View log" bit just tells the shell to open the log file, versus trying to read it and then send that to notepad (which doesn't work with the new beta NP in win11). Plus some other minor fixes.
> 

The tray app gets the log from the service because the tray app was designed to be able to work stand alone on another machine on the network. That's how I use it, I have the tray app running on my main pc so I can easily manage my plex instance. It was pretty nasty and can be done better, I don't think it should directly open the file as that breaks the intention of the tray application.

I had thought about abandoning the tray application all together and managing the service through a web app, that would be pretty easy to do and let us move away from WCF all together.

The pull request for icons was ages ago from a different user name, is that you?

**Comment by d8ahazard** [comment]
Well s*it. I think I just broke a bunch of stuff then with the logging.
I'll have to rethink that one now.

A web UI would be cool, but I'm still partial to the tray app for how I
normally use it.

And the icon - no, not mine, just curious.
