### ISSUE TITLE
Changing PmsService user account resets PLEX Server

### ISSUE THREAD

**Issue by roughnecks** [cjmurph/PmsService#56]
Hello.

I had to change the user account used to run PmsService and since then my PLEX Server went offline with all its libraries..

Is there a reason for this and a way to prevent it from happening again?

Thanks

**Comment by TechieGuy12** [comment]
Hi,
This is unrelated to the PmsService, however, I will help out as best I can.

The Plex settings and databases are specific to a user. When you change users, all the settings and databases are stored with the previous user, so they aren't available to the new user.

You can, however, move all your Plex settings from one user to another. You can read the details about how to do it here: [https://www.plexopedia.com/plex-media-server/windows/moving-plex-media-server-different-user-account/](https://www.plexopedia.com/plex-media-server/windows/moving-plex-media-server-different-user-account/).

**Comment by roughnecks** [comment]
Thanks, I already read that after what happened. The fact is, I didn't change user on Windows, I only changed the user which runs the service.

**Comment by cjmurph** [comment]
The user the service runs as is the profile the library is created in. If you change that user, you will have a different library as @TechieGuy12 mentioned.
