### ISSUE TITLE
Install Info

### ISSUE THREAD

**Issue by arrmo** [cjmurph/PmsService#6]
Hi,

Sorry, but as the Plex Forum is still down ... can you perhaps provide the install instructions here?

I have tried to just have Plex start as a scheduled task (run directly, or powershell), but it seems that I have to be logged in to run Plex Media Server, even if it's not interacting with the desktop? Weird ... :-(.

Thanks!

**Comment by cjmurph** [comment]
Hi,

The forums are up again, but I guess I should add a FAQ or something here.

**Comment by arrmo** [comment]
Yep, see the forums back up. Thanks!!!
