### ISSUE TITLE
Mention location.txt

### ISSUE THREAD

**Issue by nequam** [cjmurph/PmsService#60]
Really useful that you can put the location of the plex media server in location.txt in C:\Users\%username%\AppData\Local\Plex Service.  It allows me to use it with 64 bit Plex.

Wanted to put this note here to remind me of how I fixed it after reading the source code.

THANK YOU!

**Comment by Gaevonn** [comment]
Could you supply the format you used in the location.txt file?  I have tried a few things and can see where you found the reference to the location.txt file, but have not been able to get it to see my custom path.  Thank You.

**Comment by Gaevonn** [comment]
LoL... it never occured to me that i needed to put the full path and executable in that file, i thought just the path.  I worked it out.  Thanks.
