### ISSUE TITLE
404 After manual update

### ISSUE THREAD

**Issue by reloxx13** [cjmurph/PmsService#61]
Heya,

since a few weeks i have the problem that i get a 404 error on the plex webpage after triggering an update manual.

When plex updates itself over night, it has no problem.

I dont know where to start searching for this issue :S

I found an old issue here and it might be the same with PmsService since the new update in June.   

https://github.com/TechieGuy12/PlexServerAutoUpdater/issues/8

Latest Plex Beta Versions and running on Win10x64.

> The service now watches the logs to detect an update and will wait until it's finished before attempting a restart.

Maybe this is not working correctly and starting plex too early because detection doesnt work when running/starting an update manual? 

I looked through plex update and pmsservice logs but didnt find something striking, as the update and starting works. Its their webserver not finding the web ui.

Maybe here are others with the same issue using PmsService to confirm this issue when they trigger updates manual.

The next step i would to is downgrade PmsService and see if this fixes the manual updates.

**Comment by cjmurph** [comment]
Hi,
When you say manual update, do you mean you click update through the plex web interface?
This has traditionally been a very risky move prior to pms service version 1.2.
I took a pull request for 1.2 that was supposed to remedy the problem, however I have not personally tested this. I still update by going to my server, stopping plex via the service tray application, run the plex installer, then restart via the tray application.
