### ISSUE TITLE
Will this work with the new Plex x64 version in beta now?

### ISSUE THREAD

**Issue by MichaelKing1832** [cjmurph/PmsService#63]
Announced here: [https://forums.plex.tv/t/preview-plex-media-server-for-windows-64-bit-version/801401](https://forums.plex.tv/t/preview-plex-media-server-for-windows-64-bit-version/801401)

**Comment by bradleykorn** [comment]
According to the notes from [Release 1.2.0](https://github.com/cjmurph/PmsService/releases/tag/v1.2.0):
> I have also tested this with an upcoming 64 bit version of plex and it's working as expected.

**Comment by cjmurph** [comment]
When I installed the 64 bit version, it worked for me straight away.
If you have any issues, there is a file called location.txt where you can put the full path to the plex executable and it will work.

**Comment by rudgardel** [comment]
The location.txt tip worked for me.
Just adding that I had to create this file because it didn't exist in my installation.

**Comment by andi2022** [comment]
For me it's not working.
I have installed Plex on a custom path. I have created the location.txt in the pms program directory.

Plex install dir
F:\Plex

[location.txt](https://github.com/cjmurph/PmsService/files/9759325/location.txt)
[PlexService20221011.log](https://github.com/cjmurph/PmsService/files/9759329/PlexService20221011.log)

Or i  am doing something wrong.

**Comment by andi2022** [comment]
Good to know.
You need to create the location.txt not in the program directory from pms.
The location.txt need to be placed in your appdata local.
"%localappdata%\Plex Service"

**Comment by cjmurph** [comment]
you can now specify the location in the settings dialog (v1.2.1) if you get stuck.
