### ISSUE TITLE
Request: Scheduled restarts

### ISSUE THREAD

**Issue by PStewardEB** [cjmurph/PmsService#64]
I have been having issues with Plex after a certain release and currently have to manually stop it via Plex Service Tray and start it again everyday (to restore all my posters). Is it possible to have a scheduled restart in the future?

Note: Even a command line feature to restart would work that I could call from Windows scheduler.

Thanks!

**Comment by cjmurph** [comment]
I've been having the same issue, but I'm not keen to add this as it's just a band-aid for a Plex bug, which hopefully will be fixed in their next release

**Comment by PStewardEB** [comment]
https://forums.plex.tv/t/loss-of-posters-part-2/793193/12

I agree, its been unresolved for a while now. Anyways a command line -stop -start -restart is useful anyways.

**Comment by NGRhodes** [comment]
You could use a combination of the windows task scheduler and the `net restart <service name>' command, no need to rely on the plex service tray application.

**Comment by cjmurph** [comment]
I still have this issue with plex, but I'm not going to put a scheduled restart option in, they have a bug to fix on their end.
