### ISSUE TITLE
Support for 64-bit Plex Media Server?

### ISSUE THREAD

**Issue by saltedlolly** [cjmurph/PmsService#65]
Are there any issues using this with the 64-bit version of Plex Media Server?

**Comment by RDultsin** [comment]
+1

Was wondering the same thing now that I see 64-bit version of Plex Server for Windows available to download.

**Comment by cjmurph** [comment]
I tested it and it worked fine for me, others have said they need to use the location.txt file to specify the location.

**Comment by cpbreton** [comment]
> I tested it and it worked fine for me, others have said they need to use the location.txt file to specify the location.

Where does the location.txt file go and how is it used?

**Comment by cjmurph** [comment]
the new release (1.2.1) allows you to specify the location of the exe in the settings. It should also be stronger at finding it on it's own.
