### ISSUE TITLE
Double Clicking Icon in the Notification area closes the app

### ISSUE THREAD

**Issue by kravena** [cjmurph/PmsService#7]
When double clicking the notification icon, the program is closed because the EXIT option is the very last option in the list.

Ideally, double clicking the icon would open the Plex Web Manager page to access the server as per the original Plex icon which is no longer visible due to being run as a service.

**Comment by cjmurph** [comment]
Good idea, I'll add it to my list of things to do.

**Comment by cjmurph** [comment]
now in 1.1.1. Thanks.
