### ISSUE TITLE
Cannot update my settings

### ISSUE THREAD

**Issue by hengnv** [cjmurph/PmsService#72]
When I try to update the settings, the save button is always disabled.  I have tried it when the plex service running and not (via the app and the service control panel)

**Comment by cjmurph** [comment]
Can you post a screen shot? If it's disabled, the settings are most likely not valid

**Comment by hengnv** [comment]
Here is the screen shot:  
![image](https://user-images.githubusercontent.com/24882836/215371104-2008fac8-4cf2-4e1d-b0e6-0a7297db8b32.png)

I have made sure the UNC path is valid.

**Comment by hengnv** [comment]
This is how the settings dialog shows up.  The only thing I changed was adding the drive mapping.

**Comment by cjmurph** [comment]
ok, the default is 8787, try setting it to that. must have been lost somewhere along the way. I just checked on my install and its populating fine.

**Comment by materrac** [comment]
I had the same issue - changing port to 8787 solved it for me.  Thx

**Comment by squeaky369** [comment]
Just wanted to report, new install and the service port does not auto fill. I was having the same issue until I put the service port in, then it started to work and was able to add mappings and save settings.
