### ISSUE TITLE
Cannot re-install Plex Service

### ISSUE THREAD

**Issue by Roban1967** [cjmurph/PmsService#75]
I recently uninstalled Plex Service per the instructions posted, and redownloaded the 1.2.1.0 install file.  In addition to deleting the Plex Service folder in <user>/appdata/local, I also deleted the temp folder there.  Confirmed the Plex service is not present.  Rebooted the PC after completing the uninstall.

When I run the install, I get to the first panel, and when I click Next, nothing happens.  No errors or response from the install wizard.  I can click Cancel and after confirming I want exist the install, I can click Finish and leave the install wizard.

I can start Plex Media Server no problem.

Any suggestions?  Thanks!

**Comment by cjmurph** [comment]
Honestly, no idea. Have you tried turning it off and on again? It should just work like a fresh install.

**Comment by Roban1967** [comment]
Hard reboot of the PC solved the problem.  The service install process completed successfully.
