### ISSUE TITLE
Cannot reinstall Plex Media Service

### ISSUE THREAD

**Issue by pcg79** [cjmurph/PmsService#79]
This is the same as #75 .  Figured I'd open a new one instead of resurrecting that one.  But I can do that, if you'd rather.

OS: Windows 11
PlexService version: 1.2.1.0, running via .msi file

I had originally installed Plex Media Service just fine and it was running correctly.  I ran into some issues with it as I tried to fix a port conflict between it / Plex and Readarr so I decided to just uninstall and reinstall it.

I uninstalled Plex Media Server following the directions as written.  I did notice that, even after a reboot, some files were left behind and the Plex Service was still started.  I stopped it, deleted the leftover PlexService directory in `c:\Program Files(x86)\` and went ahead and deleted the `c:\Users\plex_user\AppData\Local\Plex Service` directory.  I've confirmed no Plex Service exists in Services and no Plex related apps are running in Task Manager.

I've redownloaded the .msi file just in case.  And I've fully turned off and back on my machine at least twice during this process including after confirming everything was deleted.

I open the .msi file.  I click Next and nothing happens.  I've waited several minutes just in case and still nothing.  If you have any ideas, I'm all ears.

**Comment by cjmurph** [comment]
Honestly, I don't know. I can only assume that the installer failed while trying to uninstall and the manual removal of the files with remnant registry entries is the issue. I have no idea why it would just hang, is it still listed in the Add/remove programs list? What version of windows are you using?

**Comment by pcg79** [comment]
Doh, I feel foolish.  Sure enough it still existed in Add/remove programs.  I ran that uninstaller and now the installer is working.  Thanks for that.
