### ISSUE TITLE
Windows Server 2012 Core Experience?

### ISSUE THREAD

**Issue by RogerSik** [cjmurph/PmsService#9]
Hello,

do have someone experience with PmsService and Windows Server 2012 Core?

Greetings
Roger

**Comment by novakin** [comment]
Its working well

**Comment by ZeroDeth** [comment]
Hello Roger,

PmsService working very well for 8 months now under windows 2012 R2 never facing
any issues even once, always doing Plex regular updates in time but manualy.
Thanks

On 11 February 2016 at 22:44, Novakin < notifications@github.com > wrote:
Its working well

**Comment by cjmurph** [comment]
I use it on server 2012 at work without isseus. Are you having problems?

**Comment by RogerSik** [comment]
Hey,

no i have no problems. My question was how it works with Server 2012 Core (the only cmd & powershell) version of windows server.

**Comment by cjmurph** [comment]
It will work the same as any other service in that environment. Should be fine. I don't have the ability to test it though.

**Comment by lrdfang** [comment]
cjmurph, what options are you using to get this to install headless? I am trying to install it on a Server 2016 container and it keeps failing on your custom create user section, with error: CreateUser:  Error 0x80070103: failed to read attributes from custom action data. I think it is because since I am running via a CLI with no interaction I am missing the username variables but I don't know what I need to use for the options.

**Comment by cjmurph** [comment]
There's no option to do a silent install. I can investigate, not sure when though.

**Comment by cjmurph** [comment]
@lrdfang this works for me

msiexec /i PlexService_1.1.0.msi SERVICE_USERNAME="domain\username" SERVICE_PASSWORD="mypassword" /quiet

**Comment by lrdfang** [comment]
Great I will give it a shot when I am home and can work on the server some more. I figured it was something like that I just wasn't sure the right variables to use. I will let you know if it works.

**Comment by cjmurph** [comment]
lrdfang, how did you go? can I close this issue?

**Comment by lrdfang** [comment]
I never got it working on the server 2016 build I was using. I ran into other issues with it and contributed it to the beta stage of the OS. I have to do a upgrade to the retail 2016. I don't have a problem with you closing out as I might be going a different route and I don't think what I was doing is possible to do now with changes microsoft has made.
